# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AnalysisOfSatelliteImages
                                 A QGIS plugin
 ...
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-16
        copyright            : (C) 2021 by Andrada Lorena Sandu
        email                : andrada.sandu28@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AnalysisOfSatelliteImages class from file AnalysisOfSatelliteImages.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .analysis_of_satellite_images import AnalysisOfSatelliteImages
    return AnalysisOfSatelliteImages(iface)
